# shipping server setup
- name: shipping server setup
  hosts: shipping
  become: yes

  tasks:
  #install maven and mysql
  - name: install maven
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  
  # install mysql python libraries
  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL

  # create system user
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user

  # remove app directory
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  # create app directory
  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  # delete shipping file
  - name: delete shipping file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  # copying the shipping file
  - name: copying the shipping file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  # extract the archive file
  - name: unarchive the file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  # install maven dependencies
  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  # move jar file
  - name: move the jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  # copy shipping service file
  - name: copy shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  # import shipping data into mysql
  - name: import shipping data into mysql
    community.mysql.mysql_db:
      name: all
      state: import
      login_host: mysql.ellamma.fun
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  # shipping service daemon-reload, enable, start
  - name: shipping service daemon-reload, enable, start
    ansible.builtin.systemd_service:
      name: shipping
      daemon_reload: yes
      enabled: yes
      state: started
      daemon_reload: true
      state: started
      enabled: true